name: diffuser
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10.2
  - pip
  - patchelf
  - gym
  - pip:
      - pip
      - setuptools
      - -f https://download.pytorch.org/whl/torch_stable.html
      - numpy
      - mujoco-py
      - matplotlib
      - torch
      - typed-argument-parser
      - git+https://github.com/Farama-Foundation/d4rl#egg=d4rl
      - scikit-image
      - scikit-video
      - gitpython
      - einops
      - ffmpeg
      - ffprobe
      - pillow
      - tqdm
      - pandas
      - wandb
      - flax
      - jax
      - ray
      - crcmod
      - google-api-python-client
      - cryptography
      - git+https://github.com/JannerM/doodad.git@janner
      - gdown
