name: diffuser
channels:
- defaults
- conda-forge
- menpo  # Added for glfw3
dependencies:
- python=3.8
- pip=24.0
- patchelf=0.17.2
- setuptools=63.2.0
- wheel=0.38.4
- cython=0.29.36
- glew=2.1.0  # Added OpenGL dependency
- glfw3=3.2.1  # Added OpenGL dependency
- mesalib=18.3.1  # Added for rendering
- libglu=9.0.0  # Added OpenGL dependency
- pip:
    - -f https://download.pytorch.org/whl/torch_stable.html
    - numpy>=1.24.0
    - gym==0.18.0
    - mujoco-py==2.1.2.14  # Exact version that worked for you
    - matplotlib==3.3.4
    - torch==1.9.1+cu111
    - typed-argument-parser
    - git+https://github.com/Farama-Foundation/d4rl@f2a05c0d66722499bf8031b094d9af3aea7c372b#egg=d4rl
    - scikit-image==0.17.2
    - scikit-video==1.1.11
    - gitpython
    - einops
    - ffmpeg
    - ffprobe
    - pillow==7.2.0
    - tqdm
    - pandas
    - wandb
    - flax==0.4.0
    - jax==0.2.21
    - jaxlib==0.4.13
    - ray==2.0.0
    - pyopengl==3.1.9  # Added for rendering
    - pyopengl-accelerate==3.1.9  # Added for rendering
    - crcmod
    - google-api-python-client
    - cryptography
    - git+https://github.com/JannerM/doodad.git@janner
    - gdown>=4.6.0